/* Generated by automated build script */
#define SNAPSHOT
#define TEXTVER "Development snapshot 2018-11-08.453a149"
#define SSHVER "-Snapshot-2018-11-08.453a149"
#define BINARY_VERSION 0,70,1492,0
#define SOURCE_COMMIT "453a1499101f027c72eaf2e36b58c8884776af7a"
